using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Projectile : MonoBehaviour {
    [SerializeField]
    private Transform target = null;
    [SerializeField]
    private float speed = 1f;

    private void Update() {
        if (target == null) {
            return;
        }

        transform.LookAt(GetAimLocation());
        transform.Translate(Vector3.forward * speed * Time.deltaTime);
    }

    private Vector3 GetAimLocation() {
        CapsuleCollider targetCapsule = target.GetComponent<CapsuleCollider>();

        if (targetCapsule == null) {
            return target.position;
        }

        return target.position + Vector3.up * targetCapsule.height / 2;
    }
}
